### ISSUE TITLE
UNIX / Windows?

### ISSUE THREAD

**Issue by blokhin** [adamgreen/CHiP-Capi#1]
Since this is the C code, I'd expect it's pretty much feasible to compile it at the other BLE-enabled platforms, such as Raspberry or Windows, isn't it? Or am I missing something?

PS the docs are written with such a care! Great work.

**Comment by adamgreen** [comment]
> Since this is the C code, I'd expect it's pretty much feasible to compile it at the other BLE-enabled platforms, such as Raspberry or Windows, isn't it? Or am I missing something?

I did write this library so that it should be easier to port. The code in https://github.com/adamgreen/CHiP-Capi/blob/master/capi/chip.c is meant to build for any platform. The macOS specific code is provided via a transport layer in https://github.com/adamgreen/CHiP-Capi/blob/master/osxble/osxble.m  This transport specific code would need to be replaced with Linux or Windows specific code to provide BLE functionality on those platforms.

> PS the docs are written with such a care! Great work.

Thanks!

**Comment by adamgreen** [comment]
Reopen if you have any other questions about porting this library to other platforms and I will be happy to answer them.
